# General settings
source: src
# Site settings
title: Iurii Kucherov
email: yuyokk@gmail.com
description: >
  Web Developer with a passion to make the Web a better place.
  JavaScript, AngularJS and Bootstrap full time engineer and moonlight Wordpress freelancer.
baseurl: ""
url: "http://iurii.ninja"
twitter_username: yuyokk
github_username:
# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
